// main.dart
// Initializes Firebase and loads AuthGate() to handle authentication state.

import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:taskapp/screens/authgate.dart';
import 'firebase_options.dart'; // auto-generated by flutterfire configure

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'ToDo App',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.indigo,
        useMaterial3: true,
      ),
      home: const AuthGate(),
    );
  }
}
